### ISSUE TITLE
b31ngD3v

### ISSUE THREAD

**Issue by keikoro** [keikoro/GHmsg#2]
@b31ngD3v I noticed an inconsistency issue between your handle (`b31ngD3v`) and account name (`b3!ngD3v`). Not good for the brand, just saying...

**Comment by b31ngD3v** [comment]
Hey bud, first of all thanks for informing.
and you're saying that someone is using my name, right ? So can you please share the username of that account who is using my name, so that I can take further action. Thank you again. 😊

**Comment by b31ngd3v** [comment]
Hmm, thanks buddy for sharing your thoughts. I'm thinking of it.
